# Generated by Django 5.2 on 2025-04-09 18:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('call_time', models.DateTimeField()),
                ('priority', models.CharField(max_length=50)),
                ('discussion', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_name', models.CharField(max_length=100)),
                ('Support_name', models.CharField(default='', max_length=20)),
                ('first_follow_up', models.CharField(default='', max_length=500)),
                ('second_follow_up', models.CharField(default='', max_length=500)),
                ('third_follow_up', models.CharField(default='', max_length=500)),
                ('id_unico', models.IntegerField(unique=True)),
                ('time_finish', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qta.equipment')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qta.place')),
            ],
        ),
    ]
