# Generated by Django 4.2.4 on 2023-09-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20)),
                ('call_time', models.DateTimeField()),
                ('priority', models.CharField(max_length=20)),
                ('discussion', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('equipment', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=20)),
            ],
        ),
    ]
