# Generated by Django 5.2 on 2025-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Support_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
