# Generated by Django 5.2 on 2025-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0002_alter_ticket_support_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='first_follow_up',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='second_follow_up',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='third_follow_up',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
