# Generated by Django 4.2.4 on 2023-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0002_rename_source_ticket_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_follow',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
