# Generated by Django 5.2 on 2025-04-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0003_alter_ticket_first_follow_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_unico',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
