# Generated by Django 4.2.4 on 2023-09-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0003_ticket_first_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='first_follow',
        ),
    ]
