# Generated by Django 4.2.4 on 2023-09-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0008_alter_ticket_first_follow_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='first_follow_up',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='second_follow_up',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='third_follow_up',
            field=models.CharField(default='', max_length=500),
        ),
    ]
