# Generated by Django 4.2.4 on 2023-10-30 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0009_alter_ticket_first_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
