# Generated by Django 4.2.4 on 2023-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0011_ticket_support_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph1', models.ImageField(upload_to='graphics/')),
                ('graph2', models.ImageField(upload_to='graphics/')),
                ('graph3', models.ImageField(upload_to='graphics/')),
                ('graph4', models.ImageField(upload_to='graphics/')),
                ('graph5', models.ImageField(upload_to='graphics/')),
                ('graph6', models.ImageField(upload_to='graphics/')),
            ],
        ),
    ]
