# Generated by Django 4.2.4 on 2023-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0012_graphics'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='id_unico',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphics',
            name='id',
            field=models.CharField(max_length=20),
        ),
    ]
