# Generated by Django 4.2.4 on 2023-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0013_graphics_id_unico_alter_graphics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics',
            name='graph1',
            field=models.ImageField(upload_to='qta/images/'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='graph2',
            field=models.ImageField(upload_to='qta/images/'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='graph3',
            field=models.ImageField(upload_to='qta/images/'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='graph4',
            field=models.ImageField(upload_to='qta/images/'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='graph5',
            field=models.ImageField(upload_to='qta/images/'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='graph6',
            field=models.ImageField(upload_to='qta/images/'),
        ),
    ]
