# Generated by Django 4.2.4 on 2023-11-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0014_alter_graphics_graph1_alter_graphics_graph2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graphics',
        ),
    ]
